// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7kwqTdSEAeZJf8_0dq4JKS4O4Ght8wc8',
    appId: '1:689774487685:web:f8f141224f810f75ba21ec',
    messagingSenderId: '689774487685',
    projectId: 'flutterfire-ui-c7cde',
    authDomain: 'flutterfire-ui-c7cde.firebaseapp.com',
    storageBucket: 'flutterfire-ui-c7cde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsVG1vw7DbMauin6joItjf0OKRuuE2G3k',
    appId: '1:689774487685:android:d28d436ea8c7b139ba21ec',
    messagingSenderId: '689774487685',
    projectId: 'flutterfire-ui-c7cde',
    storageBucket: 'flutterfire-ui-c7cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx9Z7EChCB4GZ_8bQVaC4RsYzDtJ18W0k',
    appId: '1:689774487685:ios:758d6cd133e8c9d1ba21ec',
    messagingSenderId: '689774487685',
    projectId: 'flutterfire-ui-c7cde',
    storageBucket: 'flutterfire-ui-c7cde.appspot.com',
    iosClientId: '689774487685-tqnamalo14f01ktnufqaspirnmkri2c3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx9Z7EChCB4GZ_8bQVaC4RsYzDtJ18W0k',
    appId: '1:689774487685:ios:fbeb529521781822ba21ec',
    messagingSenderId: '689774487685',
    projectId: 'flutterfire-ui-c7cde',
    storageBucket: 'flutterfire-ui-c7cde.appspot.com',
    iosClientId: '689774487685-o84oqpaurk8me9j3tl49pcvqq54vpddp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthApp.RunnerTests',
  );
}
